# CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=52154 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_sub_model/independent" COMP_LOSS.TYPE 'independent' MODEL.PRETRAIN True SUB_MODEL.GRAD_PROJ False SUB_MODEL.PROJ_W_M False BN_TRACK True DATA.BATCH_SIZE 64
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=5184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_sub_model/4 sub model cos exp 0.5" COMP_LOSS.TYPE 'proj_with_cosine_sim' MODEL.PRETRAIN True SUB_MODEL.GRAD_PROJ True SUB_MODEL.PROJ_W_M True BN_TRACK True SUB_MODEL.SPARSITY [0.2,0.4,0.6,0.8] DATA.BATCH_SIZE 64 SUB_MODEL.COS_SIM.EXP 0.5
# CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=15184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_sub_model/4 sub model" COMP_LOSS.TYPE 'proj_with_cosine_sim' MODEL.PRETRAIN True SUB_MODEL.GRAD_PROJ True SUB_MODEL.PROJ_W_M True BN_TRACK True SUB_MODEL.SPARSITY [0.2,0.4,0.6,0.8] DATA.BATCH_SIZE 64 NEW_MODEL.WEIGHT_PATH '/data/sunyushuai/FCL_submodel/FCL_ViT/output/mobile_sub_model/4 sub model/lmdb-gldv2/new_resnet_softmax_advbct/mobile_net/lr0.1_wd0.0005/run1/lmdb-gldv2_end2end_resnet18_epoch_010.pth' SUB_MODEL.COS_SIM.EXP 0.5
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=42184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_sub_model/independent" COMP_LOSS.TYPE 'independent' DATA.BATCH_SIZE 64
# switch
CUDA_VISIBLE_DEVICES=1 python  train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 1 OUTPUT_DIR "output/mobile_switch/100%/" MODEL.TYPE 'mobile_switch' SUB_MODEL.USE_SWITCHNET True COMP_LOSS.TYPE 'independent' BN_TRACK True DATA.BATCH_SIZE 64 SNET.WIDTH_MULT_LIST [1.0] SUB_MODEL.PARENT_SPARSITY 1.0 
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=5184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_switch/80%/" MODEL.TYPE 'mobile_switch' SUB_MODEL.USE_SWITCHNET True COMP_LOSS.TYPE 'independent' BN_TRACK True DATA.BATCH_SIZE 64 SNET.WIDTH_MULT_LIST [0.8944] SUB_MODEL.PARENT_SPARSITY 0.8944 
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=5184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_switch/60%/" MODEL.TYPE 'mobile_switch' SUB_MODEL.USE_SWITCHNET True COMP_LOSS.TYPE 'independent' BN_TRACK True DATA.BATCH_SIZE 64 SNET.WIDTH_MULT_LIST [0.7746] SUB_MODEL.PARENT_SPARSITY 0.7746
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=5184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_switch/40%/" MODEL.TYPE 'mobile_switch' SUB_MODEL.USE_SWITCHNET True COMP_LOSS.TYPE 'independent' BN_TRACK True DATA.BATCH_SIZE 64 SNET.WIDTH_MULT_LIST [0.6325] SUB_MODEL.PARENT_SPARSITY 0.6325 
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=5184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_switch/20%/" MODEL.TYPE 'mobile_switch' SUB_MODEL.USE_SWITCHNET True COMP_LOSS.TYPE 'independent' BN_TRACK True DATA.BATCH_SIZE 64 SNET.WIDTH_MULT_LIST [0.4472] SUB_MODEL.PARENT_SPARSITY 0.4472


# SFSC
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=5184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_switch/sfsc bct-s loss/" MODEL.TYPE 'mobile_switch' SUB_MODEL.USE_SWITCHNET True COMP_LOSS.TYPE 'SFSC' BN_TRACK True DATA.BATCH_SIZE 32 SNET.WIDTH_MULT_LIST [0.8944,0.7746,0.6325,0.4472,1.0] SUB_MODEL.PARENT_SPARSITY 1.0 SNET.USE_SFSC_LOSS False SUB_MODEL.SPARSITY [0.2,0.4,0.6,0.8] SUB_MODEL.GRAD_PROJ True BN_TRACK True 

# test
# CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=5184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_sub_model/test/" COMP_LOSS.TYPE 'proj_with_cosine_sim' BN_TRACK True DATA.BATCH_SIZE 128 SUB_MODEL.ONLY_TEST_PARENT False COMP_LOSS.ONLY_TEST True NEW_MODEL.WEIGHT_PATH './output/model_to_test/mobilenet/lmdb-gldv2_end2end_resnet18_epoch_030.pth' SUB_MODEL.SPARSITY [0.2,0.4,0.6] SUB_MODEL.ADAPTIVE_BN True  EVAL.DATASET 'rparis6k'
# CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=5184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/mobile_net.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_sub_model/test/" COMP_LOSS.TYPE 'proj_with_cosine_sim' BN_TRACK True  DATA.BATCH_SIZE 128 SUB_MODEL.ONLY_TEST_PARENT False COMP_LOSS.ONLY_TEST True NEW_MODEL.WEIGHT_PATH './output/model_to_test/mobilenet/lmdb-gldv2_end2end_resnet18_epoch_030.pth' SUB_MODEL.SPARSITY [0.8,0.9,0.95] SUB_MODEL.ADAPTIVE_BN True  EVAL.DATASET 'rparis6k'
