# CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=25184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/resnext.yaml NUM_GPUS 2 OUTPUT_DIR "output/resnext/4 sub model cos exp 0.5" COMP_LOSS.TYPE 'proj_with_cosine_sim' MODEL.PRETRAIN False SUB_MODEL.GRAD_PROJ True SUB_MODEL.PROJ_W_M True BN_TRACK True SUB_MODEL.SPARSITY [0.2,0.4,0.6,0.8] DATA.BATCH_SIZE 64 SUB_MODEL.COS_SIM.EXP 0.5
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=35284 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/resnext.yaml NUM_GPUS 2 OUTPUT_DIR "output/resnext/switch independent 1.0" COMP_LOSS.TYPE 'independent' MODEL.PRETRAIN False SUB_MODEL.GRAD_PROJ False BN_TRACK True SNET.WIDTH_MULT_LIST [1.0] DATA.BATCH_SIZE 64 MODEL.TYPE 'resnext_switch' SUB_MODEL.USE_SWITCHNET True SUB_MODEL.PARENT_SPARSITY 1.0
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=35284 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/resnext.yaml NUM_GPUS 2 OUTPUT_DIR "output/resnext_new/switch independent 0.8" COMP_LOSS.TYPE 'independent' MODEL.PRETRAIN False SUB_MODEL.GRAD_PROJ False BN_TRACK True SNET.WIDTH_MULT_LIST [0.8944] DATA.BATCH_SIZE 64 MODEL.TYPE 'resnext_switch' SUB_MODEL.USE_SWITCHNET True
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=35284 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/resnext.yaml NUM_GPUS 2 OUTPUT_DIR "output/resnext_new/switch independent 0.6" COMP_LOSS.TYPE 'independent' MODEL.PRETRAIN False SUB_MODEL.GRAD_PROJ False BN_TRACK True SNET.WIDTH_MULT_LIST [0.7746] DATA.BATCH_SIZE 64 MODEL.TYPE 'resnext_switch' SUB_MODEL.USE_SWITCHNET True
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=35284 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/resnext.yaml NUM_GPUS 2 OUTPUT_DIR "output/resnext_new/switch independent 0.4" COMP_LOSS.TYPE 'independent' MODEL.PRETRAIN False SUB_MODEL.GRAD_PROJ False BN_TRACK True SNET.WIDTH_MULT_LIST [0.6325] DATA.BATCH_SIZE 64 MODEL.TYPE 'resnext_switch' SUB_MODEL.USE_SWITCHNET True
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=35284 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/resnext.yaml NUM_GPUS 2 OUTPUT_DIR "output/resnext_new/switch independent 0.2" COMP_LOSS.TYPE 'independent' MODEL.PRETRAIN False SUB_MODEL.GRAD_PROJ False BN_TRACK True SNET.WIDTH_MULT_LIST [0.4472] DATA.BATCH_SIZE 64 MODEL.TYPE 'resnext_switch' SUB_MODEL.USE_SWITCHNET True


# SFSC
# CUDA_VISIBLE_DEVICES=2,3 python -m torch.distributed.launch --nproc_per_node=2 --master_port=35184 train.py --expe_name new_resnet_softmax_advbct --config-file ./configs/finetune/sub_model/resnext.yaml NUM_GPUS 2 OUTPUT_DIR "output/mobile_switch/sfsc bct-s loss/" MODEL.TYPE 'resnext_switch' SUB_MODEL.USE_SWITCHNET True COMP_LOSS.TYPE 'SFSC' BN_TRACK True DATA.BATCH_SIZE 6 SNET.WIDTH_MULT_LIST [0.8944,0.7746,0.6325,0.4472,1.0] SUB_MODEL.PARENT_SPARSITY 1.0 SNET.USE_SFSC_LOSS False SUB_MODEL.SPARSITY [0.2,0.4,0.6,0.8] SUB_MODEL.GRAD_PROJ True BN_TRACK True 
