_BASE_: "../../base-finetune.yaml"
RUN_N_TIMES: 200
SYNC_BN: False
BN_TRACK: True
DATA:
  NAME: "retrieval-inshop"
  DATASET_TYPE: "shop"
  DATAPATH: "./data/In-shop_Clothes_Retrieval_Benchmark/Img"  #TODO: need to specify here
  BATCH_SIZE: 64
  MULTILABEL: False
  RANDOM: True
  # MPerClass: 4
  LENGTH: 25882
  MEMORY_RATIO: 0.5

MODEL:
  TYPE: "resnet"
  SAVE_CKPT: True
  MOMENTUM: False
  MOMENTUM_M: 0.999
  PROJECTION_LAYERS: 0 # 有一层投影层
  PROJECTION_DIM: 256
  DATA: 
    FEATURE: resnet18
    NUMBER_CLASSES: 3997
    TRAIN_RATIO: 1.0


LOSS:
  TYPE: softmax
  USE_XBM: False

COMP_LOSS:
  TYPE: 'uncertainty'
  WEIGHT: 1.0
  ONLY_TEST: False

SOLVER:
  TYPE: 'submodel_compatible'
  BASE_LR: 0.1 #
  WEIGHT_DECAY: 0.0005
  OPTIMIZER: SGD # or adamw
  LOG_EVERY_N: 20
  TOTAL_EPOCH: 200
  # MILESTONES: [5,10,20]
  MILESTONES: [50,100,150]

EVAL:
  SKIP_EVAL: False
  SAVE_DIR: './test_results'
  RECALL_RANK: [1, 2, 4, 8]
  INTERVAL: 10

SUB_MODEL:
  COM_LOSS_SCALE: 1.0
  # SPARSITY: [0.2,0.4,0.6,0.9]
  SPARSITY: [0.5]
  RANDOM_SPARSITY: False
  ONLY_TEST_PARENT: True
  GRAD_SCALE: False
  DEEPCOPY: True
  SUB_MODEL_LOSS_TYPE: 'cls'
  BCT_S: False
  SLICE_SUBMODEL: False
  FIXBN: True
  FREEZEW_M: False
  GRAD_PROJ: False
  ADD_KL_LOSS: False
  ADD_KL_SCALE: False
  PROJ_W_M: False