NUM_GPUS: 1
NUM_SHARDS: 1
OUTPUT_DIR: ""
RUN_N_TIMES: 1
MODEL:
  TRANSFER_TYPE: "end2end"
  TYPE: "vit"
  DATA:
    FEATURE: "sup_vitb16_224"
    TRAIN_RATIO: 1.0
    NUMBER_CLASSES: -1
SOLVER:
  SCHEDULER: "cosine"
  WARMUP_STEP: 2000
  OPTIMIZER: "adamw"
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0001
  LOG_EVERY_N: 100
  TOTAL_EPOCH: 100
  PATIENCE: 300
DATA:
  NAME: ""
  DATAPATH: ""
  BATCH_SIZE: 384
  NUM_WORKERS: 8
LOSS:
  TYPE: "softmax"